# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\UI\ServerWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ServerWindow(object):
    def setupUi(self, ServerWindow):
        ServerWindow.setObjectName("ServerWindow")
        ServerWindow.resize(380, 370)
        ServerWindow.setIconSize(QtCore.QSize(0, 0))
        self.centralwidget = QtWidgets.QWidget(ServerWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 1, 3, 1, 1)
        self.txf_send = QtWidgets.QLineEdit(self.centralwidget)
        self.txf_send.setObjectName("txf_send")
        self.gridLayout.addWidget(self.txf_send, 2, 1, 1, 1)
        self.btn_starsv = QtWidgets.QPushButton(self.centralwidget)
        self.btn_starsv.setObjectName("btn_starsv")
        self.gridLayout.addWidget(self.btn_starsv, 0, 1, 1, 1)
        self.btn_send = QtWidgets.QPushButton(self.centralwidget)
        self.btn_send.setObjectName("btn_send")
        self.gridLayout.addWidget(self.btn_send, 2, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 2, 1, 1)
        self.txf_receive = QtWidgets.QTextEdit(self.centralwidget)
        self.txf_receive.setReadOnly(True)
        self.txf_receive.setObjectName("txf_receive")
        self.gridLayout.addWidget(self.txf_receive, 1, 1, 1, 1)
        ServerWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ServerWindow)
        self.statusbar.setObjectName("statusbar")
        ServerWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ServerWindow)
        QtCore.QMetaObject.connectSlotsByName(ServerWindow)

    def retranslateUi(self, ServerWindow):
        _translate = QtCore.QCoreApplication.translate
        ServerWindow.setWindowTitle(_translate("ServerWindow", "Servidor"))
        self.btn_starsv.setText(_translate("ServerWindow", "Start Server"))
        self.btn_send.setText(_translate("ServerWindow", "Send"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ServerWindow = QtWidgets.QMainWindow()
    ui = Ui_ServerWindow()
    ui.setupUi(ServerWindow)
    ServerWindow.show()
    sys.exit(app.exec_())
